### ISSUE TITLE
crash when used with REI search

### ISSUE THREAD

**Issue by Trickster29** [grim3212/AssortedTech#7]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_11654(net.minecraft.class_2769)" because "state" is null
	at com.grim3212.assorted.tech.client.model.BridgeBaseBakedModel.getQuads(BridgeBaseBakedModel.java:160)
	at com.grim3212.assorted.tech.client.model.BridgeBaseBakedModel.getQuads(BridgeBaseBakedModel.java:174)
	at com.grim3212.assorted.lib.client.model.loader.FabricBakedModelDelegate.emitItemQuads(FabricBakedModelDelegate.java:178)
	at com.grim3212.assorted.lib.client.model.loader.FabricBakedModelDelegate.lambda$emitItemQuads$3(FabricBakedModelDelegate.java:174)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at com.grim3212.assorted.lib.client.model.loader.FabricBakedModelDelegate.emitItemQuads(FabricBakedModelDelegate.java:174)
	at com.grim3212.assorted.lib.client.model.loader.FabricBakedModelDelegate.emitItemQuads(FabricBakedModelDelegate.java:167)
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:109)
	at net.minecraft.class_918.handler$blo000$indium$hook_renderItem(class_918.java:1055)
	at net.minecraft.class_918.method_23179(class_918.java:138)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:267)
	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.render(ForwardingEntryRenderer.java:42)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:199)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:421)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.drawCurrentEntry(EntryListStackEntry.java:157)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:376)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:250)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:143)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:110)
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:347)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:244)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$23(RoughlyEnoughItemsCoreClient.java:424)
	at net.minecraft.class_465.handler$zdo000$architectury$renderBackground(class_465.java:722)
	at net.minecraft.class_465.method_25394(class_465.java:98)
	at net.minecraft.class_485.method_25394(class_485.java:28)
	at net.minecraft.class_481.method_25394(class_481.java:731)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Assorted Tech 7.0.2
REI 11.0.597
Minecraft 1.19.4
Fabric

Reproduce:
Search "iron" in REI usually leads to REI crashing

I fixed this by adding a if before state.getValue() to check if state was not null. and this seems to stop the crash however I am not sure if this is how you'd want it permanently fixed

**Comment by grim3212** [comment]
Thanks for the report! I am just going to make it so the bridge piece actually has an item model. The new versions that will be uploaded shortly should fix this.
